### ISSUE TITLE
bit.ly external url

### ISSUE THREAD

**Issue by Flecart** [csunibo/strategia-aziendale#11]
Ho rimosso con b32e9f25d43c6832ad647d0e9118b62ef37e276e un link bit.ly aggiunto qualche ora fa 6c251ec1de3cbf14d478581f78ae06ab7d3fbfd5.
Puntava a https://ngljcb.github.io/project_17140_coinbase/, che potrebbe essere ok anche da mettere come link, che ha contenuti interattivi che da pdf non si vedono su un progetto di strategia.
Però non penso che far passare da bit.ly e trackare tutte le visite da csunibo sia ok.

**Comment by foxyseta** [comment]
@ngljcb sono d'accordo con @Flecart. È ok anche per te?

**Comment by ngljcb** [comment]
@foxyseta @Flecart d'accordo, anche per me va bene.. ho sistemato, grazie!
