### ISSUE TITLE
eliminare la repo inattivo: ipim-strategia-aziendale

### ISSUE THREAD

**Issue by ngljcb** [csunibo/strategia-aziendale#13]
ciao @ali-benny, vale anche per questo repo.. posso eliminarlo?

**Comment by foxyseta** [comment]
Analogo a https://github.com/csunibo/laboratorio-di-applicazioni-mobili/issues/12. Abbiamo deciso di eliminare la repo `ipim-strategia-aziendale` che è un duplicato di `strategia-aziendale`.
